services:

  nginxsrv1:
    build: .
    ports: 
      - "8081:80"
    volumes:
      - ./nginxsrv1.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginxsrv
  
  nginxsrv2:
    build: .
    ports: 
      - "8082:80"
    volumes:
      - ./nginxsrv2.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginxsrv
  
  nginxsrv_load_balancer:
    build: .
    ports: 
      - "8080:80"
    volumes:
      - ./load_balancer.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginxsrv

networks:
  nginxsrv:
    driver: bridge